/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookLogsRouteImport } from './routes/webhook-logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRoslagstakWebhookRouteImport } from './routes/api/public/roslagstak-webhook'

const WebhookLogsRoute = WebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoslagstakWebhookRoute =
  ApiPublicRoslagstakWebhookRouteImport.update({
    id: '/api/public/roslagstak-webhook',
    path: '/api/public/roslagstak-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/settings'
    | '/webhook-logs'
    | '/api/public/roslagstak-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/settings'
    | '/webhook-logs'
    | '/api/public/roslagstak-webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/settings'
    | '/webhook-logs'
    | '/api/public/roslagstak-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  WebhookLogsRoute: typeof WebhookLogsRoute
  ApiPublicRoslagstakWebhookRoute: typeof ApiPublicRoslagstakWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook-logs': {
      id: '/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/webhook-logs'
      preLoaderRoute: typeof WebhookLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roslagstak-webhook': {
      id: '/api/public/roslagstak-webhook'
      path: '/api/public/roslagstak-webhook'
      fullPath: '/api/public/roslagstak-webhook'
      preLoaderRoute: typeof ApiPublicRoslagstakWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  WebhookLogsRoute: WebhookLogsRoute,
  ApiPublicRoslagstakWebhookRoute: ApiPublicRoslagstakWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
