/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookLogsRouteImport } from './routes/webhook-logs'
import { Route as UppdateraKontoRouteImport } from './routes/uppdatera-konto'
import { Route as SlutfordaRouteImport } from './routes/slutforda'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrislistaRouteImport } from './routes/prislista'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PagaendeRouteImport } from './routes/pagaende'
import { Route as OfferteradeRouteImport } from './routes/offerterade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as EgenkontrollerRouteImport } from './routes/egenkontroller'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BokadeRouteImport } from './routes/bokade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobbIndexRouteImport } from './routes/jobb.index'
import { Route as EgenkontrollerIndexRouteImport } from './routes/egenkontroller.index'
import { Route as OffertNyRouteImport } from './routes/offert.ny'
import { Route as KalkylLeadIdRouteImport } from './routes/kalkyl.$leadId'
import { Route as JobbJobIdRouteImport } from './routes/jobb.$jobId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EgenkontrollerInstruktionerRouteImport } from './routes/egenkontroller.instruktioner'
import { Route as ApiSendSelfChecksRouteImport } from './routes/api/send-self-checks'
import { Route as ApiProcessWorkOrderRouteImport } from './routes/api/process-work-order'
import { Route as ApiAiPitchRouteImport } from './routes/api/ai-pitch'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicRoslagstakWebhookRouteImport } from './routes/api/public/roslagstak-webhook'
import { Route as ApiPublicLookupInviteRouteImport } from './routes/api/public/lookup-invite'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicSelfCheckPdfSplatRouteImport } from './routes/api/public/self-check-pdf.$'
import { Route as ApiPublicHooksSendBookingRemindersRouteImport } from './routes/api/public/hooks/send-booking-reminders'

const WebhookLogsRoute = WebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UppdateraKontoRoute = UppdateraKontoRouteImport.update({
  id: '/uppdatera-konto',
  path: '/uppdatera-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const SlutfordaRoute = SlutfordaRouteImport.update({
  id: '/slutforda',
  path: '/slutforda',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrislistaRoute = PrislistaRouteImport.update({
  id: '/prislista',
  path: '/prislista',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagaendeRoute = PagaendeRouteImport.update({
  id: '/pagaende',
  path: '/pagaende',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteradeRoute = OfferteradeRouteImport.update({
  id: '/offerterade',
  path: '/offerterade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const EgenkontrollerRoute = EgenkontrollerRouteImport.update({
  id: '/egenkontroller',
  path: '/egenkontroller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BokadeRoute = BokadeRouteImport.update({
  id: '/bokade',
  path: '/bokade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbIndexRoute = JobbIndexRouteImport.update({
  id: '/jobb/',
  path: '/jobb/',
  getParentRoute: () => rootRouteImport,
} as any)
const EgenkontrollerIndexRoute = EgenkontrollerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EgenkontrollerRoute,
} as any)
const OffertNyRoute = OffertNyRouteImport.update({
  id: '/offert/ny',
  path: '/offert/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkylLeadIdRoute = KalkylLeadIdRouteImport.update({
  id: '/kalkyl/$leadId',
  path: '/kalkyl/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbJobIdRoute = JobbJobIdRouteImport.update({
  id: '/jobb/$jobId',
  path: '/jobb/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EgenkontrollerInstruktionerRoute =
  EgenkontrollerInstruktionerRouteImport.update({
    id: '/instruktioner',
    path: '/instruktioner',
    getParentRoute: () => EgenkontrollerRoute,
  } as any)
const ApiSendSelfChecksRoute = ApiSendSelfChecksRouteImport.update({
  id: '/api/send-self-checks',
  path: '/api/send-self-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessWorkOrderRoute = ApiProcessWorkOrderRouteImport.update({
  id: '/api/process-work-order',
  path: '/api/process-work-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPitchRoute = ApiAiPitchRouteImport.update({
  id: '/api/ai-pitch',
  path: '/api/ai-pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoslagstakWebhookRoute =
  ApiPublicRoslagstakWebhookRouteImport.update({
    id: '/api/public/roslagstak-webhook',
    path: '/api/public/roslagstak-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLookupInviteRoute = ApiPublicLookupInviteRouteImport.update({
  id: '/api/public/lookup-invite',
  path: '/api/public/lookup-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSelfCheckPdfSplatRoute =
  ApiPublicSelfCheckPdfSplatRouteImport.update({
    id: '/api/public/self-check-pdf/$',
    path: '/api/public/self-check-pdf/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendBookingRemindersRoute =
  ApiPublicHooksSendBookingRemindersRouteImport.update({
    id: '/api/public/hooks/send-booking-reminders',
    path: '/api/public/hooks/send-booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/bokade': typeof BokadeRoute
  '/dashboard': typeof DashboardRoute
  '/egenkontroller': typeof EgenkontrollerRouteWithChildren
  '/kalender': typeof KalenderRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/offerterade': typeof OfferteradeRoute
  '/pagaende': typeof PagaendeRoute
  '/personal': typeof PersonalRoute
  '/prislista': typeof PrislistaRoute
  '/settings': typeof SettingsRoute
  '/slutforda': typeof SlutfordaRoute
  '/uppdatera-konto': typeof UppdateraKontoRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/ai-pitch': typeof ApiAiPitchRoute
  '/api/process-work-order': typeof ApiProcessWorkOrderRoute
  '/api/send-self-checks': typeof ApiSendSelfChecksRoute
  '/egenkontroller/instruktioner': typeof EgenkontrollerInstruktionerRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/jobb/$jobId': typeof JobbJobIdRoute
  '/kalkyl/$leadId': typeof KalkylLeadIdRoute
  '/offert/ny': typeof OffertNyRoute
  '/egenkontroller/': typeof EgenkontrollerIndexRoute
  '/jobb/': typeof JobbIndexRoute
  '/api/public/lookup-invite': typeof ApiPublicLookupInviteRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/send-booking-reminders': typeof ApiPublicHooksSendBookingRemindersRoute
  '/api/public/self-check-pdf/$': typeof ApiPublicSelfCheckPdfSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/bokade': typeof BokadeRoute
  '/dashboard': typeof DashboardRoute
  '/kalender': typeof KalenderRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/offerterade': typeof OfferteradeRoute
  '/pagaende': typeof PagaendeRoute
  '/personal': typeof PersonalRoute
  '/prislista': typeof PrislistaRoute
  '/settings': typeof SettingsRoute
  '/slutforda': typeof SlutfordaRoute
  '/uppdatera-konto': typeof UppdateraKontoRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/ai-pitch': typeof ApiAiPitchRoute
  '/api/process-work-order': typeof ApiProcessWorkOrderRoute
  '/api/send-self-checks': typeof ApiSendSelfChecksRoute
  '/egenkontroller/instruktioner': typeof EgenkontrollerInstruktionerRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/jobb/$jobId': typeof JobbJobIdRoute
  '/kalkyl/$leadId': typeof KalkylLeadIdRoute
  '/offert/ny': typeof OffertNyRoute
  '/egenkontroller': typeof EgenkontrollerIndexRoute
  '/jobb': typeof JobbIndexRoute
  '/api/public/lookup-invite': typeof ApiPublicLookupInviteRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/send-booking-reminders': typeof ApiPublicHooksSendBookingRemindersRoute
  '/api/public/self-check-pdf/$': typeof ApiPublicSelfCheckPdfSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/bokade': typeof BokadeRoute
  '/dashboard': typeof DashboardRoute
  '/egenkontroller': typeof EgenkontrollerRouteWithChildren
  '/kalender': typeof KalenderRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/offerterade': typeof OfferteradeRoute
  '/pagaende': typeof PagaendeRoute
  '/personal': typeof PersonalRoute
  '/prislista': typeof PrislistaRoute
  '/settings': typeof SettingsRoute
  '/slutforda': typeof SlutfordaRoute
  '/uppdatera-konto': typeof UppdateraKontoRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/api/ai-pitch': typeof ApiAiPitchRoute
  '/api/process-work-order': typeof ApiProcessWorkOrderRoute
  '/api/send-self-checks': typeof ApiSendSelfChecksRoute
  '/egenkontroller/instruktioner': typeof EgenkontrollerInstruktionerRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/jobb/$jobId': typeof JobbJobIdRoute
  '/kalkyl/$leadId': typeof KalkylLeadIdRoute
  '/offert/ny': typeof OffertNyRoute
  '/egenkontroller/': typeof EgenkontrollerIndexRoute
  '/jobb/': typeof JobbIndexRoute
  '/api/public/lookup-invite': typeof ApiPublicLookupInviteRoute
  '/api/public/roslagstak-webhook': typeof ApiPublicRoslagstakWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/send-booking-reminders': typeof ApiPublicHooksSendBookingRemindersRoute
  '/api/public/self-check-pdf/$': typeof ApiPublicSelfCheckPdfSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/bokade'
    | '/dashboard'
    | '/egenkontroller'
    | '/kalender'
    | '/leads'
    | '/login'
    | '/offerterade'
    | '/pagaende'
    | '/personal'
    | '/prislista'
    | '/settings'
    | '/slutforda'
    | '/uppdatera-konto'
    | '/webhook-logs'
    | '/api/ai-pitch'
    | '/api/process-work-order'
    | '/api/send-self-checks'
    | '/egenkontroller/instruktioner'
    | '/email/unsubscribe'
    | '/jobb/$jobId'
    | '/kalkyl/$leadId'
    | '/offert/ny'
    | '/egenkontroller/'
    | '/jobb/'
    | '/api/public/lookup-invite'
    | '/api/public/roslagstak-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/send-booking-reminders'
    | '/api/public/self-check-pdf/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/bokade'
    | '/dashboard'
    | '/kalender'
    | '/leads'
    | '/login'
    | '/offerterade'
    | '/pagaende'
    | '/personal'
    | '/prislista'
    | '/settings'
    | '/slutforda'
    | '/uppdatera-konto'
    | '/webhook-logs'
    | '/api/ai-pitch'
    | '/api/process-work-order'
    | '/api/send-self-checks'
    | '/egenkontroller/instruktioner'
    | '/email/unsubscribe'
    | '/jobb/$jobId'
    | '/kalkyl/$leadId'
    | '/offert/ny'
    | '/egenkontroller'
    | '/jobb'
    | '/api/public/lookup-invite'
    | '/api/public/roslagstak-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/send-booking-reminders'
    | '/api/public/self-check-pdf/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/bokade'
    | '/dashboard'
    | '/egenkontroller'
    | '/kalender'
    | '/leads'
    | '/login'
    | '/offerterade'
    | '/pagaende'
    | '/personal'
    | '/prislista'
    | '/settings'
    | '/slutforda'
    | '/uppdatera-konto'
    | '/webhook-logs'
    | '/api/ai-pitch'
    | '/api/process-work-order'
    | '/api/send-self-checks'
    | '/egenkontroller/instruktioner'
    | '/email/unsubscribe'
    | '/jobb/$jobId'
    | '/kalkyl/$leadId'
    | '/offert/ny'
    | '/egenkontroller/'
    | '/jobb/'
    | '/api/public/lookup-invite'
    | '/api/public/roslagstak-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/send-booking-reminders'
    | '/api/public/self-check-pdf/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  BokadeRoute: typeof BokadeRoute
  DashboardRoute: typeof DashboardRoute
  EgenkontrollerRoute: typeof EgenkontrollerRouteWithChildren
  KalenderRoute: typeof KalenderRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OfferteradeRoute: typeof OfferteradeRoute
  PagaendeRoute: typeof PagaendeRoute
  PersonalRoute: typeof PersonalRoute
  PrislistaRoute: typeof PrislistaRoute
  SettingsRoute: typeof SettingsRoute
  SlutfordaRoute: typeof SlutfordaRoute
  UppdateraKontoRoute: typeof UppdateraKontoRoute
  WebhookLogsRoute: typeof WebhookLogsRoute
  ApiAiPitchRoute: typeof ApiAiPitchRoute
  ApiProcessWorkOrderRoute: typeof ApiProcessWorkOrderRoute
  ApiSendSelfChecksRoute: typeof ApiSendSelfChecksRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  JobbJobIdRoute: typeof JobbJobIdRoute
  KalkylLeadIdRoute: typeof KalkylLeadIdRoute
  OffertNyRoute: typeof OffertNyRoute
  JobbIndexRoute: typeof JobbIndexRoute
  ApiPublicLookupInviteRoute: typeof ApiPublicLookupInviteRoute
  ApiPublicRoslagstakWebhookRoute: typeof ApiPublicRoslagstakWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksSendBookingRemindersRoute: typeof ApiPublicHooksSendBookingRemindersRoute
  ApiPublicSelfCheckPdfSplatRoute: typeof ApiPublicSelfCheckPdfSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook-logs': {
      id: '/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/webhook-logs'
      preLoaderRoute: typeof WebhookLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uppdatera-konto': {
      id: '/uppdatera-konto'
      path: '/uppdatera-konto'
      fullPath: '/uppdatera-konto'
      preLoaderRoute: typeof UppdateraKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slutforda': {
      id: '/slutforda'
      path: '/slutforda'
      fullPath: '/slutforda'
      preLoaderRoute: typeof SlutfordaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prislista': {
      id: '/prislista'
      path: '/prislista'
      fullPath: '/prislista'
      preLoaderRoute: typeof PrislistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagaende': {
      id: '/pagaende'
      path: '/pagaende'
      fullPath: '/pagaende'
      preLoaderRoute: typeof PagaendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerterade': {
      id: '/offerterade'
      path: '/offerterade'
      fullPath: '/offerterade'
      preLoaderRoute: typeof OfferteradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egenkontroller': {
      id: '/egenkontroller'
      path: '/egenkontroller'
      fullPath: '/egenkontroller'
      preLoaderRoute: typeof EgenkontrollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokade': {
      id: '/bokade'
      path: '/bokade'
      fullPath: '/bokade'
      preLoaderRoute: typeof BokadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobb/': {
      id: '/jobb/'
      path: '/jobb'
      fullPath: '/jobb/'
      preLoaderRoute: typeof JobbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egenkontroller/': {
      id: '/egenkontroller/'
      path: '/'
      fullPath: '/egenkontroller/'
      preLoaderRoute: typeof EgenkontrollerIndexRouteImport
      parentRoute: typeof EgenkontrollerRoute
    }
    '/offert/ny': {
      id: '/offert/ny'
      path: '/offert/ny'
      fullPath: '/offert/ny'
      preLoaderRoute: typeof OffertNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkyl/$leadId': {
      id: '/kalkyl/$leadId'
      path: '/kalkyl/$leadId'
      fullPath: '/kalkyl/$leadId'
      preLoaderRoute: typeof KalkylLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobb/$jobId': {
      id: '/jobb/$jobId'
      path: '/jobb/$jobId'
      fullPath: '/jobb/$jobId'
      preLoaderRoute: typeof JobbJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egenkontroller/instruktioner': {
      id: '/egenkontroller/instruktioner'
      path: '/instruktioner'
      fullPath: '/egenkontroller/instruktioner'
      preLoaderRoute: typeof EgenkontrollerInstruktionerRouteImport
      parentRoute: typeof EgenkontrollerRoute
    }
    '/api/send-self-checks': {
      id: '/api/send-self-checks'
      path: '/api/send-self-checks'
      fullPath: '/api/send-self-checks'
      preLoaderRoute: typeof ApiSendSelfChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-work-order': {
      id: '/api/process-work-order'
      path: '/api/process-work-order'
      fullPath: '/api/process-work-order'
      preLoaderRoute: typeof ApiProcessWorkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-pitch': {
      id: '/api/ai-pitch'
      path: '/api/ai-pitch'
      fullPath: '/api/ai-pitch'
      preLoaderRoute: typeof ApiAiPitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roslagstak-webhook': {
      id: '/api/public/roslagstak-webhook'
      path: '/api/public/roslagstak-webhook'
      fullPath: '/api/public/roslagstak-webhook'
      preLoaderRoute: typeof ApiPublicRoslagstakWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lookup-invite': {
      id: '/api/public/lookup-invite'
      path: '/api/public/lookup-invite'
      fullPath: '/api/public/lookup-invite'
      preLoaderRoute: typeof ApiPublicLookupInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/self-check-pdf/$': {
      id: '/api/public/self-check-pdf/$'
      path: '/api/public/self-check-pdf/$'
      fullPath: '/api/public/self-check-pdf/$'
      preLoaderRoute: typeof ApiPublicSelfCheckPdfSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-booking-reminders': {
      id: '/api/public/hooks/send-booking-reminders'
      path: '/api/public/hooks/send-booking-reminders'
      fullPath: '/api/public/hooks/send-booking-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EgenkontrollerRouteChildren {
  EgenkontrollerInstruktionerRoute: typeof EgenkontrollerInstruktionerRoute
  EgenkontrollerIndexRoute: typeof EgenkontrollerIndexRoute
}

const EgenkontrollerRouteChildren: EgenkontrollerRouteChildren = {
  EgenkontrollerInstruktionerRoute: EgenkontrollerInstruktionerRoute,
  EgenkontrollerIndexRoute: EgenkontrollerIndexRoute,
}

const EgenkontrollerRouteWithChildren = EgenkontrollerRoute._addFileChildren(
  EgenkontrollerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  BokadeRoute: BokadeRoute,
  DashboardRoute: DashboardRoute,
  EgenkontrollerRoute: EgenkontrollerRouteWithChildren,
  KalenderRoute: KalenderRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OfferteradeRoute: OfferteradeRoute,
  PagaendeRoute: PagaendeRoute,
  PersonalRoute: PersonalRoute,
  PrislistaRoute: PrislistaRoute,
  SettingsRoute: SettingsRoute,
  SlutfordaRoute: SlutfordaRoute,
  UppdateraKontoRoute: UppdateraKontoRoute,
  WebhookLogsRoute: WebhookLogsRoute,
  ApiAiPitchRoute: ApiAiPitchRoute,
  ApiProcessWorkOrderRoute: ApiProcessWorkOrderRoute,
  ApiSendSelfChecksRoute: ApiSendSelfChecksRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  JobbJobIdRoute: JobbJobIdRoute,
  KalkylLeadIdRoute: KalkylLeadIdRoute,
  OffertNyRoute: OffertNyRoute,
  JobbIndexRoute: JobbIndexRoute,
  ApiPublicLookupInviteRoute: ApiPublicLookupInviteRoute,
  ApiPublicRoslagstakWebhookRoute: ApiPublicRoslagstakWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksSendBookingRemindersRoute:
    ApiPublicHooksSendBookingRemindersRoute,
  ApiPublicSelfCheckPdfSplatRoute: ApiPublicSelfCheckPdfSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
